config/routes.rb
Brewklok::Application.routes.draw do
  resources :recipes do
    member do 
      get "run"
    end
  end
  
  resources :users
  resource :session
  
  match "/about", to: "static_pages#about", via: 'get'
  root "static_pages#index"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :time, :recipe_id, :notes, :amount
  belongs_to :recipe
  
  validates :name, :time, :recipe, presence: true

  default_scope { order('time') } 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :ingredients, :user_id, :notes 
  validates :name, :user_id, presence: true
  
  has_many :ingredients, inverse_of: :recipe
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  #need to definitely fix the session_token
  attr_accessible :username, :password, :session_token
  attr_reader :password
  
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 4, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true
  after_initialize :ensure_session_token

  has_many :recipes
  has_many :ingredients, through: :recipes
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
    
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    @recipes.sort_by! {|recipe| recipe.name}
    render :index
  end
  
  def show
    @recipe = Recipe.includes(:ingredients).find(params[:id])

    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @recipe, include: :ingredients }
    end
  end
  
  def new
    render :new
  end
  
  def create
    @recipe = Recipe.new(params[:recipe])    
    @recipe.ingredients.new(params[:ingredients].values)
    
    @recipe.user_id = current_user.id if logged_in?
        
    if @recipe.save
      redirect_to recipes_url
    else
      flash[:errors] = @recipe.errors.full_messages
      render :new      
    end
  end

  def run
    @recipe = Recipe.find(params[:id])
    render :run
  end

  def update    
    Ingredient.update(params[:recipe].keys, params[:recipe].values)
        
    render json: 'Request made'.to_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    
    if user.nil?
      flash[:errors] = flash[:errors] || []
      flash[:errors] << "Credentials were wrong"
      render :new
    else
      login(user)
      flash[:success] = ["Welcome back #{user.username}!"]
      redirect_to recipes_url
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end

  def new
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @recipes = Recipe.find(:all, limit: 5, order: 'created_at desc')
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def create
    @user = User.new(username: params[:user][:username])
    @user.password = params[:user][:password]
    @user.reset_session_token!

    if @user.save
      login(@user)
      flash[:success] = ["Thank you for signing up #{@user.username}!"]
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,500' rel='stylesheet' type='text/css'>
  <title>Brewklok</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= render partial: 'shared/navbar' %>
<body>
	<!-- <div class="container"> -->
		<!-- <%= current_user.username if logged_in? %>	 -->
		<%= render partial: 'shared/flash_messages' %>
		<%= yield %>
	<!-- </div> -->
</body>
</html>

app/views/recipes/_display_edit_buttons.html.erb
<% if logged_in? %>
	<i class="glyphicon glyphicon-edit" id="edit-button" data-recipeid="<%= @recipe.id %>"
		onClick="makeRecipeEditable(event);"></i>
	
	<i class="glyphicon glyphicon-floppy-disk" id="save-button" onClick="saveRecipe();"></i>
	<i class="glyphicon glyphicon-floppy-remove" id="cancel-save-button" onClick="cancelSaveRecipe();"></i>
	</h3>
<% else %>
	<i class="glyphicon glyphicon-edit" id="edit-button" data-recipeid="<%= @recipe.id %>"></i>
	</h3>
	<p>Please <a href='<%= new_session_url %>'>login</a> to edit recipes</p>
<% end %>

app/views/recipes/_mode_dropdown.html.erb
<ul class="nav nav-pills" >
	<li class="dropdown" style="width: 50%">
    <a class="dropdown-toggle" data-toggle="dropdown" id="mode-dropdown" href="#">
      Demo Mode <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><a href="#" onClick="bh.setMode('demo');">Demo Mode (1s = 1m)</a></li>
      <li><a href="#" onClick="bh.setMode('realtime');">Brew Mode (real time)</a></li>
		</ul>
	</li>
</ul>

app/views/recipes/index.html.erb
<div class='container'>
	<h2>Brew Recipes</h2>
	<% @recipes.each do |recipe| %>
		<h3><a href="<%= recipe_url(recipe) %>"><%= recipe.name %></a></h3>
		<h4>by <%= recipe.user.username %></h4>
		<% recipe.ingredients.each do |ingredient| %>
			<li><%= ingredient.name %> - at <%= ingredient.time %> min</li>
			<% end %>
	<% end %>
</div>

app/views/recipes/new.html.erb
<div class='container'>
	<% if !logged_in? %>
		<div class='.row'>		
			<p>Please <a href='<%= new_session_url %>'>login</a> to add recipes</p>
		</div>
	<% end%>
	
	<div class="col-md-6">
		<form action="<%= recipes_url %>" method="POST" role="form" id='recipe-form'>
			<%= render partial: 'shared/auth_token'%>

			<h2>Brew Details</h2>
		  <div class="form-group">
				<label for="recipe_name">Brew name: </label>
				<input class="form-control" type="text" name="recipe[name]" value="" id="recipe_name">
				<br>
			</div>
			<h2>Ingredients <button class="btn btn-default"  onClick="addIngredientForm();return false;">+</button></h2>
			<p><input class="btn btn-success" type="submit" value="Submit Recipe" id="submit_recipe"></p>
		</form>
	</div>
</div>

<script>
	var ingredientId = 0;
	addIngredientForm();
	<% if !logged_in? %>
		$('#submit_recipe').prop('disabled', true)
	<% end%>
	//should use a JST template later
	//refers to templates/ingredient_form.js variable
</script>

app/views/recipes/run.html.erb
<div class='container'>
	<div class="jumbotron">
		<div class='row'><div class='col-md-3'></div>
		  <p class='col-md-6'>
				<a class="btn btn-success btn-lg center-block start-button" onClick="bh.start('#display-timer', recipe);" role="button">Start Timer</a>
			<a class="btn btn-info btn-lg center-block pause-button" onClick="bh.pause();" role="button" style='display: none;'>Pause</a>
			<a class="btn btn-success btn-lg center-block unpause-button" onClick="bh.unpause();" role="button" style='display: none;'>Resume</a>
			</p>
			<div class='col-md-3'></div>
		</div>

			<div class='row'>
			<h1 id="display-timer" class="text-center">00:00:00</h1>
		</div>
	</div>

	<div class="row" style="text-align: center">
	  <div class="col-md-3" id="pastIngredients"><h2>Past</h2></div>
	  <div class="col-md-6" id="currentIngredients"><h2>Current</h2></div>
	  <div class="col-md-3" id="futureIngredients"><h2>Future</h2></div>
	</div>
	
	<script>
		var bh;
		var recipe;
		loadRecipe(<%= @recipe.id %>, "../", function(resp){ 
			recipe = resp; 
			bh = new BrewHandler(recipe);
			bh.fillFuture();
		});
	</script>
</div>

app/views/recipes/show.html.erb
<div class='container'>
	<div class='row'>
		<div class="col-md-6"><h2><%= @recipe.name %></h2>
			<% if !@recipe.notes.nil? %>
				<p><%= @recipe.notes %></p>
			<% end %>			
		</div>
		<div class="col-md-3"><h1 class='show-clock-text' id='clock'>00:00:00</h1></div>
		<div class="col-md-3">
			<%= render partial: "recipes/mode_dropdown"%>
			<h1><button class="btn btn-warning" id='brew-action-button'>Begin Brew!</button></h1>
		</div>
	</div>
	<div id='graph-container' class='container'>
		<div id='graph'>			
		</div>
	</div>

	<div class='row'>
	<h3>Ingredients
		<%= render partial: 'recipes/display_edit_buttons' %>
	</div>

	<table class="table" id="ingredient-table">
		<thead>
			<tr>
				<th>Time</th>
				<th>Ingredient</th>
				<th>Amount</th>
				<th>Notes</th>
			</tr>
		</thead>

		<tbody id="ingredient-table-body">
			<% @recipe.ingredients.each do |ingredient| %>
			<tr class='ingredient-listing future' data-ingredientId="<%= ingredient.id %>">
				<td class='ingredient-attr ingredient-time'><%= ingredient.time %></td>
				<td class='ingredient-attr ingredient-name'><%= ingredient.name %></td>
				<td class='ingredient-attr ingredient-amount'><%= ingredient.amount %></td>
				<td class='ingredient-attr ingredient-notes'><%= ingredient.notes %></td>
			</tr>
	
			<script>
				addToGraph(<%= ingredient.id %>, 
											"<%= ingredient.name %>", 
											<%= ingredient.time %>, 
											<%= @recipe.ingredients.last.time + 5 %>);											
				addChangeListeners(<%= ingredient.id %>);
			</script>
			<% end %>
		</tbody>	
	</table>
</div>
	<script>
	var bh;
	var recipe;
		loadRecipe(<%= @recipe.id %>, "./", function(resp){ 
			recipe = resp; 
			recipe.totalTime = recipe.ingredients[recipe.ingredients.length-1].time + 5;
			bh = new BrewHandler(recipe);
			bh.fillFuture();
			
			addGrid(recipe.totalTime);
		});
		
	addProgressBar();
	$("#mode-dropdown").dropdown();
	bindBrewActionHandler($('#brew-action-button'));	
	</script>

app/views/shared/_auth_token.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/shared/_flash_messages.html.erb
<% if !flash[:errors].nil? %>
	<% flash[:errors].each do |error| %>
	<script>
		alertMessage('<%= error %>', 'danger');
		<% flash[:errors] = nil %>
		</script>
	<% end %>
<% end %>

<% if !flash[:success].nil? %>
	<% flash[:success].each do |success| %>
	<script>
		alertMessage('<%= success %>', 'success');
		<% flash[:success] = nil %>
		</script>
	<% end %>
<% end %>

app/views/shared/_intro.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
</div>

app/views/shared/_login_form.html.erb
<%= render partial: 'shared/auth_token' %>
<div class="row">
	<div class="input-group col-xs-6">
	  <span class="input-group-addon login-input">Username</span>
		<input class="form-control" type="text" name="user[username]" value="" id="user_username" placeholder="username">
	</div>
</div>
	<div class="row">
	<div class="input-group col-xs-6">
	  <span class="input-group-addon login-input">Password</span>
		<input class="form-control" type="password" name="user[password]" value="" id="user_password" placeholder="password">
	</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_url%>"><img src='/assets/headline-transp.png' id='nav-img'></img></a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="<%= recipes_url %>">Browse Brews</a></li>
      <li><a href="<%= new_recipe_url %>">Add A Brew</a></li>
      <li><a href="<%= about_url %>">About</a></li>
      <% if logged_in?%>
				<li><%= link_to "Logout", session_url, method: :delete %></li>
			<% else %>
				<li><%= link_to "Login", new_session_url %></li>
			<% end %>
		</ul>
</nav>

app/views/static_pages/about.html.erb
<div class='container'>
	<h1>About Brewklok</h1>
	<p>(It's freaking awesome!)</p>
	<p>Brewing beer is a great process. A lot of creativity and planning goes into every brew. However, if you're not careful it's easy to stray from your original recipe. The result will still undoubtedly taste great, but may not be what you were aiming for.</p>
	<p>Brewklok helps you create and organize recipes, but more importantly runs a live timer for your recipe that keeps you on track by reminding you when to remove and add ingredients. Never miss an ingredient again!</p>
	
	<p><a href='<%= recipe_url(2)%>'> Test out a brew in demo or live mode</a></p>
	<p>This project was also created as a final project for App Academy by <a href="http://fadetoproductions.com">Ryan von Kunes Newton</a>. The technologies used were Ruby on Rails and heavy amounts of Javascript. <a href="https://github.com/newtonry/Brewklok">Here's the GitHub repo</a>!</p>

	<div class='row'>
		<img src="/assets/full-logo-transp.png" class="col-md-12" id='about-logo'></img>
	</div>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron" id="front-page-jumbo">
	<div class='jumbotron-info col-md-12'>
		<div class='row'>
			
			<div class="col-md-2">
				<img src="/assets/brewklok-white-cropped.png" id="index-logo" class="col-md-3"></img>
			</div>
			<div class="col-md-10">
			  <h1>Welcome to Brewklok!</h1>
			  <p>Ready to brew some beer?</p>
			  <!-- <p><a href="<%= about_url %>" class="btn btn-primary btn-lg" role="button">Learn more</a></p> -->
			  <p><a href="<%= recipe_url(2) %>" class="btn btn-primary btn-lg" role="button">Test a brew!</a></p>
			</div>
		</div>
	</div>
</div>

<div class='container'>
	<h2>Recent Brews</h2>
	<% @recipes.each do |recipe| %>
		<h3><a href="<%= recipe_url(recipe) %>"><%= recipe.name %></a></h3>
		<p><%= recipe.notes %></p>
	<% end %>
</div>

app/views/users/new.html.erb
<div class='container'>
	<h1>Register</h1>
	<p>Although not required, this will allow you to manage and track your brews</p>
		<div class='well'>	
			<form action="<%= users_url %>" method="POST">
				<%= render partial: 'shared/login_form' %>
				<br>
			<p><input class="btn btn-success" type="submit" value="Join"></p>
		</form>
	</div>
</div>

app/views/users/show.html.erb
<div class='container'>
	<h2><%= @user.username %></h2>
		<% @user.recipes.reverse.each do |recipe| %>
			<li><%= recipe.name %></li>
		<% end %>
	</div>